use crate::application::ports::ClipboardSource;
use crate::domain::clipboard_chart::ClipboardRevision;

/// Reads the clipboard of the host operating system.
pub struct SystemClipboard;

impl ClipboardSource for SystemClipboard {
    fn revision(&self) -> Option<ClipboardRevision> {
        platform::revision()
    }

    fn read_text(&self) -> Option<String> {
        platform::read_text()
    }
}

#[cfg(target_os = "macos")]
mod platform {
    use objc2_app_kit::{NSPasteboard, NSPasteboardTypeString};
    use objc2_foundation::{NSArray, NSString};

    use crate::domain::clipboard_chart::ClipboardRevision;

    /// Types applications use to mark clipboard contents that observers must
    /// leave alone, such as password manager output. Honouring them is the
    /// convention for anything that watches the pasteboard.
    const CONCEALED_TYPES: &[&str] = &[
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ];

    /// `changeCount` is pasteboard metadata rather than contents, so polling it
    /// costs one integer read and never raises a paste permission alert.
    pub fn revision() -> Option<ClipboardRevision> {
        let change_count = NSPasteboard::generalPasteboard().changeCount();

        Some(ClipboardRevision::new(change_count as u64))
    }

    pub fn read_text() -> Option<String> {
        let pasteboard = NSPasteboard::generalPasteboard();
        if is_concealed(&pasteboard) {
            return None;
        }

        let string_type = unsafe { NSPasteboardTypeString };

        Some(pasteboard.stringForType(string_type)?.to_string())
    }

    /// Checks the advertised types, which is metadata and does not count as
    /// reading the contents.
    fn is_concealed(pasteboard: &NSPasteboard) -> bool {
        let concealed: Vec<_> = CONCEALED_TYPES
            .iter()
            .map(|name| NSString::from_str(name))
            .collect();

        pasteboard
            .availableTypeFromArray(&NSArray::from_retained_slice(&concealed))
            .is_some()
    }
}

#[cfg(not(target_os = "macos"))]
mod platform {
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};

    use crate::domain::clipboard_chart::ClipboardRevision;

    /// No portable change counter exists, so the text itself is hashed. Unlike
    /// the macOS change count this costs a full read on every poll.
    pub fn revision() -> Option<ClipboardRevision> {
        let text = read_text()?;
        let mut hasher = DefaultHasher::new();
        text.hash(&mut hasher);

        Some(ClipboardRevision::new(hasher.finish()))
    }

    pub fn read_text() -> Option<String> {
        arboard::Clipboard::new().ok()?.get_text().ok()
    }
}
